-- MySQL Script generated by MySQL Workbench
-- Mon Mar  9 06:16:48 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(120) NOT NULL,
  `email` VARCHAR(160) NOT NULL,
  `password_hash` VARCHAR(255) NOT NULL,
  `bio` VARCHAR(255) NULL,
  `is_active` TINYINT NULL DEFAULT 1,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`posts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`posts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `content` TEXT NOT NULL,
  `visibility` ENUM('public', 'private') GENERATED ALWAYS AS (public) VIRTUAL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `user_id`
    FOREIGN KEY (`id`)
    REFERENCES `mydb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`comments` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `post_id` INT NULL,
  `user_id` INT NULL,
  `content` TEXT NOT NULL,
  `content_at` DATETIME NOT NULL,
  `created_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `post_id`
    FOREIGN KEY (`id`)
    REFERENCES `mydb`.`posts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `user_id`
    FOREIGN KEY (`id`)
    REFERENCES `mydb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`likes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`likes` (
  `user_id` INT NOT NULL,
  `post_id` INT NOT NULL,
  `created_at` DATETIME NULL,
  PRIMARY KEY (`user_id`, `post_id`),
  INDEX `post_id_idx` (`post_id` ASC) VISIBLE,
  CONSTRAINT `user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `post_id`
    FOREIGN KEY (`post_id`)
    REFERENCES `mydb`.`posts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`audit_log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`audit_log` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `table_name` VARCHAR(64) NOT NULL,
  `operation` ENUM('INSERT', 'UPDATE', 'DELETE') NULL,
  `record_id` BIGINT NULL,
  `changed_by_user_id` INT NULL,
  `details` JSON NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

USE `mydb`;

DELIMITER $$
USE `mydb`$$
CREATE DEFINER = CURRENT_USER TRIGGER `mydb`.`audit_log_BEFORE_INSERT` BEFORE INSERT ON `audit_log` FOR EACH ROW
BEGIN
declare msg varchar(255);
declare email_existe int;

select count(*) into email_existe from users where email = new.email;
if new.email is null or new.email = '' then
	set msg = 'O campo email é de preenchimento obrigatório';
	signal sqlstate '45000' set message_text = msg;
end if;

if emails_exist >= 1 then
	set msg = 'Já existe um usuário com esse email';
	signal sqlstate'45000' set message_text = msg;
end if;
END$$

USE `mydb`$$
CREATE DEFINER = CURRENT_USER TRIGGER `mydb`.`users_AFTER_INSERT` AFTER INSERT ON `users` FOR EACH ROW
BEGIN
insert into audit_log -- envia pra audit_log, outra table
(table_name, operation, record_id, changed_by_user, details)
VALUES -- fala o que vai ser inserido na coluna do insert
('users','INSERT', new.id, new.user_id, 'usuario registrado'); -- new é pra insert/update, old para delete
END$$

USE `mydb`$$
CREATE DEFINER = CURRENT_USER TRIGGER `mydb`.`users_AFTER_UPDATE` AFTER UPDATE ON `users` FOR EACH ROW
BEGIN
insert into audit_log -- envia pra audit_log, outra table
(table_name, operation, record_id, changed_by_user, details)
VALUES -- fala o que vai ser inserido na coluna do insert
('users','UPDATE', new.id, new.user_id, 'usuario atualizado'); -- new é para valores que vão entrar ou foram alterados(insert/update) e old para valores que já existiam(delete/update)
END$$

USE `mydb`$$
CREATE DEFINER = CURRENT_USER TRIGGER `mydb`.`users_AFTER_DELETE` AFTER DELETE ON `users` FOR EACH ROW
BEGIN
insert into audit_log -- envia pra audit_log, outra table
(table_name, operation, record_id, changed_by_user, details)
VALUES -- fala o que vai ser inserido na coluna do insert
('users','DELETE', old.id, old.user_id, 'usuario apagado'); -- new é para valores que vão entrar ou foram alterados(insert/update) e old para valores que já existiam(delete/update)
END$$

USE `mydb`$$
CREATE DEFINER = CURRENT_USER TRIGGER `mydb`.`posts_BEFORE_INSERT` BEFORE INSERT ON `posts` FOR EACH ROW
BEGIN
declare post varchar(255);

if new_content is null or char_length(trim(new.content)) < 5 then
signal sqlstate '45000'
set message_text = 'Conteúdo muito curto, necessário ao menos 5 caracteres por mensagem e não pode estar vazio';
end if;
END$$

USE `mydb`$$
CREATE DEFINER = CURRENT_USER TRIGGER `mydb`.`posts_AFTER_INSERT` AFTER INSERT ON `posts` FOR EACH ROW
BEGIN
insert into audit_log -- envia pra audit_log, outra table
(table_name, operation, record_id, changed_by_user, details)
VALUES -- fala o que vai ser inserido na coluna do insert
('posts','INSERT', new.id, new.user_id, 'post feito');
END$$

USE `mydb`$$
CREATE DEFINER = CURRENT_USER TRIGGER `mydb`.`posts_AFTER_UPDATE` AFTER UPDATE ON `posts` FOR EACH ROW
BEGIN
insert into audit_log -- envia pra audit_log, outra table
(table_name, operation, record_id, changed_by_user, details)
VALUES -- fala o que vai ser inserido na coluna do insert
('posts','UPDATE', new.id, new.user_id, 'post atualizado');
END$$

USE `mydb`$$
CREATE DEFINER = CURRENT_USER TRIGGER `mydb`.`posts_AFTER_DELETE` AFTER DELETE ON `posts` FOR EACH ROW
BEGIN
INSERT INTO audit_log -- envia pra audit_log, outra table
(table_name, operation, record_id, changed_by_user, details)
VALUES -- fala o que vai ser inserido na coluna do insert
('posts','DELETE', old.id, old.user_id, 'post apagado');-- new é para valores que vão entrar ou foram alterados(insert/update) e old para valores que já existiam(delete/update)
END$$

USE `mydb`$$
CREATE DEFINER = CURRENT_USER TRIGGER `mydb`.`comments_BEFORE_INSERT` BEFORE INSERT ON `comments` FOR EACH ROW
BEGIN
declare comment varchar(255);
if new.comment is null or new.comment='' then
 set comment = 'a mensagem precisa conter ao menos 1 caractere';
	signal sqlstate '45000' set message_text = comment;
end if;
END$$

USE `mydb`$$
CREATE DEFINER = CURRENT_USER TRIGGER `mydb`.`comments_AFTER_INSERT` AFTER INSERT ON `comments` FOR EACH ROW
BEGIN
insert into audit_log
(table_name, operation, record_id, changed_by_user, details)
VALUES
('comments','INSERT', new.id, new.user_id, 'comentario registrado');
END$$

USE `mydb`$$
CREATE DEFINER = CURRENT_USER TRIGGER `mydb`.`comments_AFTER_UPDATE` AFTER UPDATE ON `comments` FOR EACH ROW
BEGIN
insert into audit_log
(table_name, operation, record_id, changed_by_user, details)
VALUES
('comments','UPDATE', new.id, new.user_id, 'comentario editado ou atualizado');
END$$

USE `mydb`$$
CREATE DEFINER = CURRENT_USER TRIGGER `mydb`.`comments_AFTER_DELETE` AFTER DELETE ON `comments` FOR EACH ROW
BEGIN
insert into audit_log
(table_name, operation, record_id, changed_by_user, details)
VALUES
('comments','DELETE', new.id, new.user_id, 'comentario removido');
END$$

USE `mydb`$$
CREATE DEFINER = CURRENT_USER TRIGGER `mydb`.`likes_BEFORE_INSERT` BEFORE INSERT ON `likes` FOR EACH ROW
BEGIN
declare post_id int;
declare alread_post int;

select count(*) into alread_post from likes where post_id = new.post_id;

if alread_post >= 1 then
	set msg = 'Curtida já adicionada';
	signal sqlstate'45000' set message_text = msg;
end if;
END$$

USE `mydb`$$
CREATE DEFINER = CURRENT_USER TRIGGER `mydb`.`likes_AFTER_INSERT` AFTER INSERT ON `likes` FOR EACH ROW
BEGIN
insert into audit_log
(table_name, operation, record_id, changed_by_user, details)
VALUES
('likes','INSERT', new.id, new.user_id, 'curtida registrada');
END$$

USE `mydb`$$
CREATE DEFINER = CURRENT_USER TRIGGER `mydb`.`likes_AFTER_UPDATE` AFTER UPDATE ON `likes` FOR EACH ROW
BEGIN
insert into audit_log
(table_name, operation, record_id, changed_by_user, details)
VALUES
('likes','UPDATE', new.id, new.user_id, 'curtida atualizada ou checada');
END$$

USE `mydb`$$
CREATE DEFINER = CURRENT_USER TRIGGER `mydb`.`likes_AFTER_DELETE` AFTER DELETE ON `likes` FOR EACH ROW
BEGIN
insert into audit_log
(table_name, operation, record_id, changed_by_user, details)
VALUES
('likes','DELETE', new.id, new.user_id, 'curtida removida');
END$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
